version: '2.1'
services:

    php:
        build: .
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - ./www/:/var/www/html
        links: 
            - bd
    bd:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        volumes: 
            - /var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=sitecompras
    app:
        image: phpmyadmin/phpmyadmin:latest
        links: 
            - bd
        restart: always
        ports: 
            - 88:80
        environment: 
            - PMA_ARBITRARY=1
        volumes:
            - /sessions
            - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
            - /custom/phpmyadmin/theme/:/www/themes/theme/
    dump:  
        build: Dumper/  
        volumes:  
            - ./Dumper/:/var/lib/  
        command: sh -c "sleep 20 && /usr/bin/mysql -h mysql -uroot -proot < /var/lib/dump.sql"  
        depends_on:  
            - bd 